.TH "abraflexi-client-config-checker" "1" "0.10" "Vítězslav Dvořák" "abraflexi-client-config"
.SH "NAME"
php-abraflexi-checker - Check php-abraflexi configuration
.br
.SH "SYNTAX"
abraflexi-client-config-checker
.br
.SH "DESCRIPTION"
Load default config file /etc/abraflexi/client.json (or use environment if config file not exist) and try to connect.
.br
in case of success return 0 exit code else exit code 1
.br
.SH "OPTIONS"
.SH "FILES"
\fI/etc/\fRabraflexi/client.json
.br

.SH "EXAMPLES"
To run this program the standard way type:
.br

abraflexi-client-config-checker
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br
.SH "SEE ALSO"
abraflexi-client-config(2)
.br
