.TH "abraflexi-client-reconfigure" "1" "0.10" "Vítězslav Dvořák" "php-abraflexi-config"
.SH "NAME"
abraflexi-client-reconfigure - Reconfigure php-abraflexi
.br
.SH "SYNTAX"
abraflexi-client-reconfigure
.br

.SH "DESCRIPTION"
Reconfigure php-abraflexi client configuration
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br

.SH "SEE ALSO"
php-abraflexi-checker(2)
.br
