.TH "abraflexi-config-export" "1" "0.10" "Vítězslav Dvořák" "php-abraflexi-config"
.SH "NAME"
abraflexi-config-export - build environment configuration file
.br
.SH "SYNTAX"
abraflexi-config-export > /etc/profile.d/abraflexi-client.sh
.br

.SH "DESCRIPTION"
Export settings as environment variable for use with programs using ENV based configuration
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br

.SH "SEE ALSO"
php-abraflexi-checker(2)
.br
