.TH "abraflexi-client-reconfigure" "1" "0.0.0" "Vitezslav Dvorak" "abraflexi-client-config"
.SH "NAME"
abraflexi-client-config-reconfigure - Reconfigure php-abraflexi config file
.br
.SH "SYNTAX"
abraflexi-client-config-reconfigure
.br

.SH "DESCRIPTION"
Asks again for AbraFlexi client configuration
.br
.SH "FILES"
\fI/etc/\fRabraflexi/client.json
.br
.SH "EXAMPLES"
To show current configuration type:
.br

abraflexi-client-config-reconfigure
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br

.SH "SEE ALSO"
php-abraflexi-checker(2)
.br
