.TH "flexibee-client-config-checker" "1" "0.10" "Vítězslav Dvořák" "flexibee-client-config"
.SH "NAME"
php-flexibee-checker - Check php-flexibee configuration
.br
.SH "SYNTAX"
php-flexibee-checker
.br
.SH "DESCRIPTION"
Load default config file /etc/flexibee/client.json and try to connect.
.br
in case of success return 0 exit code else exit code 1
.br
.SH "OPTIONS"
.SH "FILES"
\fI/etc/\fRflexibee/client.json
.br

.SH "EXAMPLES"
To run this program the standard way type:
.br

php-flexibee-checker
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br
.SH "SEE ALSO"
php-flexibee-config(2)
.br
