#!/bin/sh
# prerm script for multiflexi-abraflexi-client-check
set -e
. /usr/share/debconf/confmodule
case "$1" in
    remove)
        for file in `ls /usr/share/multiflexi-abraflexi-client-check/multiflexi/*.json`
        do
          multiflexi-json-app-remover $file
        done
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
