#!/bin/sh
# postinst script for php-flexibee-config

set -e

if [ "$1" = "configure" ]; then
    . /usr/share/debconf/confmodule
fi

cd /usr/share/php-flexibee-config
if [ -f composer.lock ] ; then
    rm -f composer.lock
fi
composer --no-plugins --no-scripts --no-dev -o install

if [ -f /usr/bin/flexibee-client-checker ]; then
    flexibee-client-checker
fi


#DEBHELPER#

exit 0
