#!/bin/sh
# postinst script for abraflexi-client-config

#export DH_VERBOSE=1

CONFIGFILE=/etc/abraflexi/client.json
set -e
. /usr/share/debconf/confmodule

composer-debian abraflexi-client-config

if [ "$1" = "configure" ]; then
    db_get abraflexi-client-config/ABRAFLEXI_URL
    abraflexi-client-config ABRAFLEXI_URL $RET
    db_get abraflexi-client-config/ABRAFLEXI_LOGIN
    abraflexi-client-config ABRAFLEXI_LOGIN $RET
    db_get abraflexi-client-config/ABRAFLEXI_PASSWORD
    abraflexi-client-config ABRAFLEXI_PASSWORD $RET
    db_get abraflexi-client-config/ABRAFLEXI_COMPANY
    abraflexi-client-config ABRAFLEXI_COMPANY $RET

    db_get abraflexi-client-config/ENVIRONMENT_ABRAFLEXI_CONFIG
    if [ "$RET" = "true" ]; then
	abraflexi-config-export > /etc/profile.d/abraflexi-client.sh
    fi

    db_get abraflexi-client-config/APACHE_ABRAFLEXI_CONFIG
    if [ "$RET" = "true" ]; then
	mkdir -p /etc/apache2/conf-available
	abraflexi-config-export > /etc/apache2/conf-available/abraflexi_env.conf
    fi

fi

abraflexi-client-config-checker

#DEBHELPER#

exit 0
